### ISSUE TITLE
Contact

### ISSUE THREAD

**Issue by NandoSangenetto** [webedia/webedia.github.io#1]
Hey @webedia, 

Can I speak with you? I work in a company named webedia and I wish to use your nickname.
Since you're not active on github, I wonder if that's possible.

Thanks

**Comment by webedia** [comment]
Hi Fernando,

We also work for a company named Webedia and we are currently using the github account.

Please choose a different github handle.

Regards,

Webedia Dev

Email: dev@webedia.com
Web: www.webedia.com
 
**********************************************
The contents of this email are strictly confidential. If you are not the intended recipient, any use, disclosure or copying of this email (including any attachments) is unauthorised and prohibited. If you have received this email in error, please notify Webedia immediately by return email and then delete the message from your system.
**********************************************
Webedia Pty Ltd   |   ACN 147 922 594   |   ABN 39 147 922 594
